// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkM64qQRxIZI8_OLAYmlYtw4kjLmCG3vk',
    appId: '1:1031541122446:web:462602d6e718b8dbc1b0df',
    messagingSenderId: '1031541122446',
    projectId: 'mockly-9d312',
    authDomain: 'mockly-9d312.firebaseapp.com',
    storageBucket: 'mockly-9d312.firebasestorage.app',
    measurementId: 'G-TBPGL20M12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMLVV9OEK7ii3djB98JkM_RnRr8KRe2fE',
    appId: '1:1031541122446:android:8e6379d75bf10a94c1b0df',
    messagingSenderId: '1031541122446',
    projectId: 'mockly-9d312',
    storageBucket: 'mockly-9d312.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSuHSW7vrVyXh-YCoLtRqLa0vZvKAtsvc',
    appId: '1:1031541122446:ios:7c1d9998eb93082ec1b0df',
    messagingSenderId: '1031541122446',
    projectId: 'mockly-9d312',
    storageBucket: 'mockly-9d312.firebasestorage.app',
    iosBundleId: 'com.example.mcq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSuHSW7vrVyXh-YCoLtRqLa0vZvKAtsvc',
    appId: '1:1031541122446:ios:7c1d9998eb93082ec1b0df',
    messagingSenderId: '1031541122446',
    projectId: 'mockly-9d312',
    storageBucket: 'mockly-9d312.firebasestorage.app',
    iosBundleId: 'com.example.mcq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkM64qQRxIZI8_OLAYmlYtw4kjLmCG3vk',
    appId: '1:1031541122446:web:fbd1f3835f333b10c1b0df',
    messagingSenderId: '1031541122446',
    projectId: 'mockly-9d312',
    authDomain: 'mockly-9d312.firebaseapp.com',
    storageBucket: 'mockly-9d312.firebasestorage.app',
    measurementId: 'G-GJSGSEC9SG',
  );
}
